kafka:
  broker_address: "localhost:29092"
  group_id: "order-service-group"
  topic: "orders"

postgres:
  host: "localhost"
  port: "5432"
  user: "user1"
  password: "123456789"
  dbname: "l0wb"

http:
  host: ""
  port: "8080"